--   Assignment 5
-- Create a view displaying the order information (Id, Title, Price, Shopper’s name, Email, Orderdate, Status),
-- with latest ordered items should be displayed first for last 60 days.
-- CREATE VIEW order_info
-- AS 
-- SELECT p.product_id,p.title,s.name,s.email,o.shopping_date,
-- CASE
--    WHEN od.shipped = TRUE THEN 'shipped'
--    WHEN od.completed = TRUE THEN 'completed'
--    WHEN od.cancelled = TRUE THEN 'cancelled'
-- END AS status FROM
-- order_detail od JOIN product p ON p.product_id = od.product_id 
-- JOIN orders o ON o.id = od.order_id JOIN
-- shopper s ON s.shopper_id = o.shopper_id
-- WHERE o.shopping_date >= NOW() - INTERVAL 60 DAY
-- ORDER BY o.shopping_date DESC;

-- Use the above view to display the Products(Items) which are in ‘shipped’ state.
-- SELECT * FROM order_info 
-- WHERE status = 'shipped';

-- Use the above view to display the top 5 most selling products.
-- SELECT product_id,title,COUNT(*) AS num_of_use FROM order_info
-- GROUP BY product_id
-- ORDER BY num_of_use DESC
-- LIMIT 5;
